class ExecutorAgent:
    """
    Executes steps generated by the planner using available tools.
    """

    def __init__(self, tools_registry):
        self.tools_registry = tools_registry

    def execute(self, steps: list):
        results = []

        for step in steps:
            results.append(f"Executed: {step}")

        return results
